---
apiVersion: v1
kind: Service
metadata:
  name: traffic02-test-redis
  labels:
    env: test
spec:
  type: ClusterIP
  selector:
    app: traffic02-test-redis-app
  ports:
  - name: traffic02-redis-service
    port: 6379
    targetPort: 6379