---
apiVersion: v1
kind: Service
metadata:
  name: rhea1228-test-redis
  labels:
    username: rhea1228
    env: test
spec:
  type: ClusterIP
  selector:
    app: rhea1228-test-redis-app
  ports:
  - name: rhea1228-redis-service
    port: 6379
    targetPort: 6379