---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhea1228-test-redis-debug
  labels:
    username: rhea1228
    env: test
    app: rhea1228-test-redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      username: rhea1228
      env: test
      app: rhea1228-test-redis-app
  template:
    metadata:
      labels:
        username: rhea1228
        env: test
        app: rhea1228-test-redis-app
    spec:
      containers:
        - name: rhea1228-test-redis-deployment
          image: redis:5.0.0