apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhea1228-test-redis-pvc
  labels:
    username: rhea1228
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi