apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traffic02-test-redis-pvc
  labels:
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi