---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic02-api-deployment
  labels:
    app: traffic02-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic02-api
  template:
    metadata:
      labels:
        app: traffic02-api
    spec:
      containers:
        - name: traffic02-api-deployment
          imagePullPolicy: Always
          image: rheebeee/traffic02-service
          command: ['python', 'api.py']
          env:
          - name: FLASK_API
            value: "api.py"
          ports:
          - name: http
            containerPort: 5000