---
apiVersion: v1
kind: Pod
metadata:
  name: hello-hw-b
  labels:
    greeting: personalized
spec:
  containers:
    - name: hello
      image: ubuntu:18.04
      env:
      - name: "NAME"
        value: "Rhea"
      command: ['sh', '-c', 'echo "Hello, $NAME!" && sleep 3600']