---
apiVersion: v1
kind: Service
metadata:
  name: rhea1228-hw07-test-flask
  labels:
    username: rhea1228
    env: test
spec:
  type: ClusterIP
  selector:
    app: rhea1228-api
  ports:
  - name: rhea1228-hw07-flask-service
    port: 5000
    targetPort: 5000